/*
 * Class: View.java
 * 
 * This class represents the front end of the music store application. It is
 * a simple text-based UI that allows the user to search/add songs, albums
 * and playlists, rate songs, and more. It interacts with the MusicStore and
 * LibraryModel classes. It contains helper methods to print the necessary
 * information for songs/albums, and contains a large main method that handles
 * the UI interactions.
 */
package main.view;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import main.database.MusicStore;
import main.database.UserDB;
import main.model.Album;
import main.model.LibraryModel;
import main.model.PlayList;
import main.model.Song;
import main.model.User;

public class View {
	
	// print a song along with its other information
	private static void printSong(Song s) {
		if (s == null) {
			System.out.println("No song with this title");
			System.out.println();
			return;
		}
		
		System.out.println("Song title: " + s.getTitle());
		System.out.println("Artist: " + s.getArtist());
		System.out.println("Album: " + s.getAlbum());
		System.out.println();
	}
	
	// print an album along with its other information
	private static void printAlbum(Album a) {
		if (a == null) {
			System.out.println("No album with this title");
			System.out.println();
			return;
		}
		
		System.out.println("Album title: " + a.getTitle());
		System.out.println("Artist: " + a.getArtist());
		System.out.println("Genre: " + a.getGenre());
		System.out.println("Year: " + a.getYear());
		System.out.println("Tracklist:");
		
		for (Song s : a.getTracklist()) {
			System.out.println(s.getTitle());
		}
		System.out.println();
	}
	
	// print each album in a list of albums
	private static void printAlbumList(ArrayList<Album> albums) {
		if (albums == null || albums.size() == 0) {
			System.out.println("No albums found");
			System.out.println();
			return;
		}
		for (Album a : albums) {
			printAlbum(a);
		}
	}
	
	// print each song in a list of songs
	private static void printSongList(ArrayList<Song> songs) {
		if (songs == null || songs.size() == 0) {
			System.out.println("No songs found");
			System.out.println();
			return;
		}
		for (Song s : songs) {
			printSong(s);
		}
	}
	
	// GENERATED BY AI
	// checks if a given string represents an integer between 1 and 5
	public static boolean isIntegerBetweenOneAndFive(String str) {
	    try {
	        int num = Integer.parseInt(str);
	        return num >= 1 && num <= 5;
	    } catch (NumberFormatException e) {
	        return false;
	    }
	}
	
	public static void main(String[] args) {
		MusicStore ms = new MusicStore();
		LibraryModel genericLibrary = new LibraryModel();
		LibraryModel library = genericLibrary;
		UserDB db = new UserDB();
		
		User currentUser = null;
		
		Scanner scanner = new Scanner(System.in);  // use to get user input
	     
	     while (true) {
	    	System.out.println("What would you like to do?");
	    	System.out.println();
	    	String input = scanner.nextLine().toLowerCase();  // store user input

	        if (input.equals("quit")) {
	        	break;
	        }
	        
	        // Create a User
	        else if (input.equals("create user")) {
	        	System.out.println("What is your username?");
	        	System.out.println();
	        	
	        	String username = scanner.nextLine().toLowerCase().strip();
	        	
	        	System.out.println("What is your password?");
	        	System.out.println();
	        	
	        	String password = scanner.nextLine().toLowerCase().strip();
	        	
	        	try {
					if (!db.addUser(username, password)) {
						System.out.println("Username is taken");
			        	System.out.println();
					}
					else {
						System.out.println("Successfully added user");
			        	System.out.println();
					}
				} catch (IOException e) {
					System.out.println("Error: could not access database");
		        	System.out.println();
				}
	        	
	        }
	        
	        // Logging in
	        else if (input.equals("login")) {
	        	System.out.println("What is your username?");
	        	System.out.println();
	        	
	        	String username = scanner.nextLine().toLowerCase().strip();
	        	
	        	System.out.println("What is your password?");
	        	System.out.println();
	        	
	        	String password = scanner.nextLine().toLowerCase().strip();
	        	
	        	if (db.loginSuccessful(username, password)) {
	        		currentUser = db.getUser(username);
	        		library = currentUser.getLibrary();
	        		System.out.println("Logged in successfully");
		        	System.out.println();
	        	}
	        	else {
	        		System.out.println("Username or password is incorrect");
		        	System.out.println();
	        	}
	        	
	        }
	        
	        // Logging out
	        else if (input.equals("log out")) {	
	        	currentUser = null;       // Reset user
	        	library = genericLibrary; // Reset library
	        	System.out.println("You are logged out");
	        	System.out.println();
	        }
	        
	        // Searching MusicStore
	        else if (input.equals("search music store")) {
	        	System.out.println("Do you want to search for song(s) or album(s)?");
	        	System.out.println();
	        	
	        	input = scanner.nextLine().toLowerCase().strip();
	        	
	        	if (input.equals("song") || input.equals("songs")) {
	        		System.out.println("By title or artist?");
		        	System.out.println();
		        	input = scanner.nextLine().toLowerCase().strip();
		        	
		        	if (input.equals("artist")) {
		        		System.out.println("Which artist?");
			        	System.out.println();
			        	input = scanner.nextLine().strip();
			        	
			        	printSongList(ms.getSongsByArtist(input));
		        	}
		        	else if (input.equals("title")) {
		        		System.out.println("Which song?");
			        	System.out.println();
			        	input = scanner.nextLine().strip();
			        	
			        	printSongList(ms.getSongByTitle(input));
			        	
		        	}
		        	else {
		        		System.out.println("This is not an option");
		        		System.out.println();
		        	}
	        	}
	        	else if (input.equals("album") || input.equals("albums")) {
	        		System.out.println("By title or artist?");
		        	System.out.println();
		        	
		        	input = scanner.nextLine().strip();
		        	
		        	if (input.equals("artist")) {
		        		System.out.println("Which artist?");
			        	System.out.println();
			        	input = scanner.nextLine().strip();
			        	
			        	printAlbumList(ms.getAlbumsByArtist(input));
		        	}
		        	else if (input.equals("title")) {
		        		System.out.println("Which album?");
			        	System.out.println();
			        	input = scanner.nextLine().strip();
			        	
			        	printAlbum(ms.getAlbumByTitle(input));
		        	}
	        	}
	        	else {
	        		System.out.println("This is not an option");
	        		System.out.println();
	        	}
	        }
	        
	        // Searching library
	        else if (input.equals("search library")) {
	        	System.out.println("What do you want to search for?");
	        	System.out.println();
	        	
	        	input = scanner.nextLine().toLowerCase().strip();
	        	
	        	if (input.equals("song") || input.equals("songs")) {
	        		System.out.println("By title or artist?");
		        	System.out.println();
		        	input = scanner.nextLine().toLowerCase().strip();
		        	
		        	if (input.equals("artist")) {
		        		System.out.println("Which artist?");
			        	System.out.println();
			        	input = scanner.nextLine().strip();
			        	
			        	printSongList(library.getSongsByArtist(input));
		        	}
		        	else if (input.equals("title")) {
		        		System.out.println("Which song?");
			        	System.out.println();
			        	input = scanner.nextLine().strip();
			        	
			        	printSong(library.getSongByTitle(input));
			        	
			        	if (ms.getSongByTitle(input) != null) {
			        		String songTitle = input;
			        		System.out.println("Get Album Info?");
				        	System.out.println();
				        	input = scanner.nextLine().strip();
				        	
				        	if (input.toLowerCase().equals("yes")) {
				        		String albumTitle = ms.getSongByTitle(songTitle).get(0).getAlbum();
				        		Album a = ms.getAlbumByTitle(albumTitle);
				        		printAlbum(a);
				        	}
			        	}
		        	}
		        	else {
		        		System.out.println("This is not an option");
		        		System.out.println();
		        	}
	        	}
	        	else if (input.equals("album") || input.equals("albums")) {
	        		System.out.println("By title or artist?");
		        	System.out.println();
		        	
		        	input = scanner.nextLine().strip();
		        	
		        	if (input.equals("artist")) {
		        		System.out.println("Which artist?");
			        	System.out.println();
			        	input = scanner.nextLine().strip();
			        	
			        	printAlbumList(library.getAlbumsByArtist(input));
		        	}
		        	else if (input.equals("title")) {
		        		System.out.println("Which album?");
			        	System.out.println();
			        	input = scanner.nextLine().strip();
			        	
			        	printAlbum(library.getAlbumByTitle(input));
		        	}
	        	}
	        	else if (input.equals("playlist") || input.equals("playlists")) {
	        		System.out.println("What is the title of the playlist?");
		        	System.out.println();
		        	
		        	input = scanner.nextLine().strip();
		        	
		        	PlayList p = library.getPlayListByName(input);
		        	
		        	if (p == null) {
		        		System.out.println("No playlist by this name");
		        		System.out.println();
		        	}
		        	else {
		        		ArrayList<Song> playlistSongs = p.getSongs();
						
						for (Song s : playlistSongs) {
							System.out.println(s.getArtist() + ": " + s.getTitle());
						}
		        	}
	        	}
	        	else {
	        		System.out.println("This is not an option");
	        		System.out.println();
	        	}
	        }
	        
	        // Add Song to library
	        else if (input.equals("add song")) {
	        	System.out.println("Which song?");
	        	System.out.println();
	        	
	        	input = scanner.nextLine().strip();
	        	
	        	library.addSong(input);
	        }
	        
	        // Add Album to library
	        else if (input.equals("add album")) {
	        	System.out.println("Which album?");
	        	System.out.println();
	        	
	        	input = scanner.nextLine().strip();
	        	
	        	library.addAlbum(input);
	        	System.out.println(input + " added.");
	        }
	        
	        // List added songs
	        else if (input.equals("list my songs")) {
	        	printSongList(library.getSongs());
	        }
	        
	        // List added artists
	        else if (input.equals("list my artists")) {
	        	ArrayList<String> artists = library.getArtists();
	        	
	        	if (artists.size() == 0) {
	        		System.out.println("No Artists");
	        		System.out.println();
	        	}
	        	else {
	        		for (String a : artists) {
	        			System.out.println(a);
	        		}
	        	}
	        }
	        
	        // List added Albums
	        else if (input.equals("list my albums")) {
	        	printAlbumList(library.getAlbums());
	        }
	        
	        // List created playlists
	        else if (input.equals("list my playlists")) {
	        	ArrayList<PlayList> playlists = library.getPlaylists();
	        	
	        	for (PlayList p : playlists) {
	        		System.out.println(p.getName());
	        	}
	        	System.out.println();
	        }
	        
	        // List favorite songs
	        else if (input.equals("list my favorite songs")) {
	        	printSongList(library.getFavorites());
	        }
	        
	        // Create a playlist
	        else if (input.equals("create playlist")) {
	        	System.out.println("What do you want to name your playlist?");
	        	System.out.println();
	        	
	        	input = scanner.nextLine().strip();
	        		        	
	        	if (library.makePlaylist(input) == null) {
	        		System.out.println("Playlist with this name already exists");
	        		System.out.println();
	        	}
	        }
	        
	        // Add song to playlist
	        else if (input.equals("add song to playlist")) {
	        	System.out.println("Which playlist?");
	        	System.out.println();
	        	
	        	String playlist = scanner.nextLine().strip();
	        	
	        	System.out.println("Which song?");
	        	System.out.println();
	        	
	        	String song = scanner.nextLine().strip();
	        	
	        	if (!library.addSongToPlayList(playlist, song)) {
	        		System.out.println("Either song or playlist does not exist");
	        		System.out.println();
	        	}
	        }
	        
	        // Remove song from playlist
	        else if (input.equals("remove song from playlist")) {
	        	System.out.println("Which playlist?");
	        	System.out.println();
	        	
	        	String playlist = scanner.nextLine().strip();
	        	
	        	System.out.println("Which song?");
	        	System.out.println();
	        	
	        	String song = scanner.nextLine().strip();
	        	
	        	if (!library.removeSongFromPlayList(playlist, song)) {
	        		System.out.println("Either song or playlist does not exist");
	        		System.out.println();
	        	}
	        }
	        
	        // Mark as Favorite
	        else if (input.equals("mark song as favorite")) {
	        	System.out.println("Which song?");
	        	System.out.println();
	        	
	        	input = scanner.nextLine().strip();
	        	
	        	Song s = library.getSongByTitle(input);
	        	
	        	if (s == null) {
	        		System.out.println("No song with this title");
	        		System.out.println();
	        	} 
	        	else {
	        		library.markAsFavorite(s.getTitle());
	        	}
	        	
	        }
	        
	        // Rate a song
	        else if (input.equals("rate a song")) {
	        	System.out.println("Which song?");
	        	System.out.println();
	        	
	        	input = scanner.nextLine().strip();
	        	
	        	Song s = library.getSongByTitle(input);
	        	
	        	if (s == null) {
	        		System.out.println("No song with this title");
	        		System.out.println();
	        	}
	        	
	        	else {
		        	System.out.println("What is the rating?");
		        	System.out.println();
		        	
		        	input = scanner.nextLine().strip();
		        	
		        	if (isIntegerBetweenOneAndFive(input)) {
		        		library.rateSong(s.getTitle(), Integer.parseInt(input));
		        	}
		        	else {
		        		System.out.println("Rating must be an integer between 1 and 5");
			        	System.out.println();
		        	}
	        	}
	        }
	        
	        // List songs by genre
	        else if (input.equals("list songs by genre")) {
	        	System.out.println("Which genre?");
	        	System.out.println();
	        	
	        	input = scanner.nextLine().strip();
	        	
	        	printSongList(library.getSongsByGenre(input));
	        }
	        
	        // Shuffle library or playlist
	        else if (input.equals("shuffle library")) {
	        	library.shuffleSongs();
	        	System.out.println("Library shuffled!");
	        }
	        
	        else if (input.equals("shuffle playlist")) {
	        	System.out.println("Enter the playlist name:");
	        	String playlistName = scanner.nextLine().strip();
	        	library.shufflePlayList(playlistName);
	        	System.out.println("Playlist shuffled!");
	        }
	        
	        // Remove song or album
	        else if (input.equals("remove song")) {
	        	System.out.println("Enter the song title:");
	        	String songTitle = scanner.nextLine().strip();
	        	
	        	System.out.println("Enter the artist:");
	        	String artist = scanner.nextLine().strip();
	        	
	        	if (library.removeSong(songTitle, artist)) {
	        		System.out.println("Song removed.");
	        	} else {
	        		System.out.println("Song not found.");
	        	}
	        }
	        
	        else if (input.equals("remove album")) {
	        	System.out.println("Enter the album title:");
	        	String albumTitle = scanner.nextLine().strip();
	        	
	        	if (library.removeAlbum(albumTitle)) {
	        		System.out.println("Album removed.");
	        	} else {
	        		System.out.println("Album not found.");
	        	}
	        }
	        
	        // Sort by title, artist, or rating
	        else if (input.equals("sort songs")) {
	        	System.out.println("What will you sort by? (title/artist/rating)");
	        	String criterion = scanner.nextLine().strip();
	        	System.out.println("Ascending or Descending? (A/D)");
	        	String order = scanner.nextLine().strip();
	        	
	        	boolean ascending = order.equalsIgnoreCase("A");
	        	List<Song> sortedSongs = library.getSortedSongs(criterion, ascending);
	        	
	        	System.out.println("Sorted Songs:");
	        	for (Song song : sortedSongs) {
	        		System.out.println(song.getTitle() + " by " + song.getArtist());
	        	}
	        	
	        }
	        
	        // Show Recently and Frequently Played Songs
	        else if (input.equals("play song")) {
	        	System.out.println("Which song?");
	        	String songTitle = scanner.nextLine().strip();
	        	library.playSong(songTitle);
	        }
	        else if (input.equals("list recently played")) {
	        	System.out.println("Recently Played Songs:");
	        	printSongList(library.getRecentlyPlayed().getSongs());
	        }
	        
	        else if (input.equals("list frequently played")) {
	        	System.out.println("Most Frequently Played Songs:");
	        	printSongList(library.getFrequentlyPlayed().getSongs());
	        }
	        
	        else {
	        	System.out.println("Invalid command, try again");
        		System.out.println();
	        }
	     
	     }
	 
	  scanner.close(); 
	  
	 }
}